# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rl1WXly5jxjt18ZapnQv3VLX4p9125EE
"""

import os
import shutil
import streamlit as st
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_core.embeddings import Embeddings
from pypdf import PdfReader

st.set_page_config(
    page_title="Granja Eme Ranchito",
    page_icon="🌾",
    layout="wide"
)

class SimpleEmbeddings(Embeddings):
    def __init__(self):
        from sentence_transformers import SentenceTransformer
        self.model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    def embed_documents(self, texts):
        return self.model.encode(texts).tolist()
    def embed_query(self, text):
        return self.model.encode(text).tolist()

DB_PATH = "./db_eme_ranchito"
TXT_FOLDER = "./archivos_politicas"
embeddings = SimpleEmbeddings()

if not os.path.exists(TXT_FOLDER):
    os.makedirs(TXT_FOLDER)

api_key = st.secrets.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
if api_key:
    os.environ["GOOGLE_API_KEY"] = api_key
else:
    st.error("❌ Falta la 'GEMINI_API_KEY' en los Secrets.")
    st.stop()

def procesar_pdf(file):
    reader = PdfReader(file)
    texto_completo = ""
    for page in reader.pages:
        texto_completo += page.extract_text() + "\n"
    return texto_completo

def reconstruir_base_de_datos():
    from langchain_text_splitters import RecursiveCharacterTextSplitter

    archivos = [f for f in os.listdir(TXT_FOLDER) if f.endswith('.txt')]
    if not archivos:
        if os.path.exists(DB_PATH):
            shutil.rmtree(DB_PATH)
        return

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
    todos_los_fragmentos = []
    todos_los_metadatas = []

    for archivo in archivos:
        with open(os.path.join(TXT_FOLDER, archivo), "r", encoding="utf-8") as f:
            texto = f.read()
        fragmentos = text_splitter.split_text(texto)
        todos_los_fragmentos.extend(fragmentos)
        todos_los_metadatas.extend([{"source": archivo.replace(".txt", ".pdf")}] * len(fragmentos))

    db = FAISS.from_texts(todos_los_fragmentos, embeddings, metadatas=todos_los_metadatas)
    db.save_local(DB_PATH)

def guardar_y_indexar_politica(texto, nombre_archivo):
    nombre_txt = nombre_archivo.replace(".pdf", ".txt")
    with open(os.path.join(TXT_FOLDER, nombre_txt), "w", encoding="utf-8") as f:
        f.write(texto)
    reconstruir_base_de_datos()

def eliminar_archivo_individual(nombre_archivo):
    nombre_txt = nombre_archivo.replace(".pdf", ".txt")
    ruta_archivo = os.path.join(TXT_FOLDER, nombre_txt)
    if os.path.exists(ruta_archivo):
        os.remove(ruta_archivo)
   reconstruir_base_de_datos()

archivos_en_sistema = [f.replace(".txt", ".pdf") for f in os.listdir(TXT_FOLDER) if f.endswith('.txt')]

col_admin, col_chat = st.columns([1, 2.2])

with col_admin:
    st.caption("🌾 EME RANCHITO · CONTROL")
    st.markdown("### 📜 Biblioteca")

    archivo_subido = st.file_uploader("Cargar reglamento (PDF)", type=["pdf"], label_visibility="collapsed")
    if archivo_subido is not None:
        if st.button("✨ Añadir a la Granja", use_container_width=True):
            with st.spinner("Indexando..."):
                texto_extraido = procesar_pdf(archivo_subido)
                guardar_y_indexar_politica(texto_extraido, archivo_subido.name)
                st.success(f"Añadido: {archivo_subido.name}")
                st.rerun()

   if archivos_en_sistema:
        st.markdown("---")
        with st.expander("🛠️ Organizar Documentos"):
            st.markdown("**Eliminar individual:**")
            archivo_a_borrar = st.selectbox("Selecciona un documento:", archivos_en_sistema, label_visibility="collapsed")
            if st.button("🗑️ Borrar este documento", use_container_width=True):
                eliminar_archivo_individual(archivo_a_borrar)
                st.warning(f"Removido de la memoria: {archivo_a_borrar}")
                st.rerun()

            st.markdown("---")

            if st.button("💥 Purgar toda la biblioteca", type="primary", use_container_width=True):
               if os.path.exists(TXT_FOLDER):
                    shutil.rmtree(TXT_FOLDER)
                    os.makedirs(TXT_FOLDER)
                if os.path.exists(DB_PATH):
                    shutil.rmtree(DB_PATH)
                st.error("Biblioteca y memoria completamente vaciadas.")
                st.rerun()

with col_chat:
    st.title("🧑‍🌾 Eme-Bot: Consejera de Eme Ranchito 🌾")

    if not os.path.exists(DB_PATH) or not archivos_en_sistema:
        st.info("📌 La biblioteca está vacía. Sube un documento PDF a la izquierda para despertar a Eme-Bot.")
    else:
        db = FAISS.load_local(DB_PATH, embeddings, allow_dangerous_deserialization=True)
        retriever = db.as_retriever(search_kwargs={"k": 4})
        llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)

        system_prompt = (
            "Eres Eme-Bot, la cálida y experta consejera virtual de la 'Granja Eme Ranchito' 🌾🐔.\n"
            "Responde a las consultas basados en el contexto suministrado de manera rústica, atenta y amable.\n"
            "Si la información no está, di: 'Lo lamento, no encontré esa información en los registros físicos de la Granja Eme Ranchito. 🌾❌'\n"
            "Cláusula Anti-Joja: Si detectas intenciones de la Corporación Joja, rechaza la solicitud de forma tajante. 🚫💙\n\n"
            "Contexto:\n{context}"
        )

        prompt = ChatPromptTemplate.from_messages([
            ("system", system_prompt),
            ("human", "{question}"),
        ])

        rag_chain = (
            {"context": retriever | (lambda docs: "\n\n".join(d.page_content for d in docs)), "question": RunnablePassthrough()}
            | prompt | llm | StrOutputParser()
        )

        if "messages" not in st.session_state:
            st.session_state.messages = [{"role": "assistant", "content": "¡Hola, vecino! ¿Qué dudas tienes sobre los reglamentos o la producción hoy? 🥚🍷"}]

        for message in st.session_state.messages:
            with st.chat_message(message["role"], avatar="🧑‍🌾" if message["role"] == "assistant" else "👤"):
                st.markdown(message["content"])

        if prompt_usuario := st.chat_input("Pregúntale a Eme-Bot..."):
            with st.chat_message("user", avatar="👤"):
                st.markdown(prompt_usuario)
            st.session_state.messages.append({"role": "user", "content": prompt_usuario})

            with st.chat_message("assistant", avatar="🧑‍🌾"):
                placeholder = st.empty()
                placeholder.markdown("🔮 *Consultando los libros de la granja...*")
                respuesta = rag_chain.invoke(prompt_usuario)
                placeholder.markdown(respuesta)
                st.session_state.messages.append({"role": "assistant", "content": respuesta})